name: California Association of Emergency Medical Technicians
favicon: null
layout_spectrum: 0.61728
typography_spectrum: 0.81448
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ffc324'
    - '#333192'
    - '#a88652'
    - '#a4a4cd'
  brandStrength: 0
  lightness: 0.125
  saturation: 0
  rhythmicContrast: 0
purpose: []
