name: California Association of Emergency Medical Technicians
favicon: null
layout_spectrum: 0.35547923133708537
typography_spectrum: 0.5331763294525445
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.7621631594374776
  lightness: 0.1212691250257194
  saturation: 0.02567672822624445
  rhythmicContrast: 0.015537791652604938
purpose: []
